name: nasa_space_view
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.18.1
  dio: ^5.3.4
  bloc: ^8.1.2
  get_it: ^7.6.4
  package_info_plus: ^4.2.0
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  bloc_test: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mock_data: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
